name: Compile TypeScript

on:
  workflow_dispatch:   # manual run
  push:
    branches:
      - main
    paths:
      - '**/*.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript to JavaScript
        run: tsc --project tsconfig.json

      - name: Commit compiled JS
        env:
          TOKEN: ${{ secrets.EXO }}  # your personal access token
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add '**/*.js'
          git diff --cached --quiet || git commit -m "Compile TypeScript to JS [skip ci]"
          git push https://$TOKEN@github.com/${{ github.repository }} HEAD:${{ github.ref }}
